# Generated by Django 3.1.7 on 2021-04-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='ikz',
            field=models.CharField(max_length=255, unique=True, verbose_name='IKZ'),
        ),
    ]
