# Generated by Django 3.1.7 on 2021-04-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0003_eort_region'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eort',
            unique_together={('lat', 'lng')},
        ),
    ]
