# Generated by Django 3.1.7 on 2021-04-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0005_eort_fm_eort_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eort',
            unique_together=set(),
        ),
    ]
