# Generated by Django 3.1.7 on 2021-04-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0006_auto_20210406_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule_ACC',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(max_length=255, verbose_name='WstKrz')),
            ],
        ),
        migrations.CreateModel(
            name='Rule_WT',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(max_length=255, verbose_name='WstKrz')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rule_acc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WZO_App.rule_acc'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rule_wt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WZO_App.rule_wt'),
        ),
    ]
