# Generated by Django 3.1.7 on 2021-04-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0007_auto_20210406_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zip_Code',
            fields=[
                ('zip_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5, verbose_name='PLZ')),
                ('city', models.CharField(max_length=255, verbose_name='Stadt')),
                ('state', models.CharField(max_length=255, verbose_name='Bundesland')),
            ],
        ),
        migrations.AlterField(
            model_name='eort',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WZO_App.zip_code'),
        ),
    ]
