# Generated by Django 3.1.7 on 2021-04-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0009_auto_20210408_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eort',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WZO_App.zip_code'),
        ),
    ]
