# Generated by Django 3.1.7 on 2021-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0010_auto_20210408_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eort',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='eort',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Longditude'),
        ),
    ]
