# Generated by Django 3.1.7 on 2021-04-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0011_auto_20210408_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='eort',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Gelöscht'),
        ),
    ]
