# Generated by Django 3.1.7 on 2021-04-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0013_auto_20210410_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.CharField(default='test', max_length=255, verbose_name='Baujahr'),
            preserve_default=False,
        ),
    ]
