# Generated by Django 3.1.7 on 2021-04-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0014_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='objgroup',
            field=models.CharField(default='test', max_length=255, verbose_name='Objektgruppe'),
            preserve_default=False,
        ),
    ]
