# Generated by Django 3.1.7 on 2021-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0015_vehicle_objgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='eort',
            name='displayable',
            field=models.BooleanField(default=False, verbose_name='Anzeigbar'),
        ),
    ]
