# Generated by Django 3.1.7 on 2021-04-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0016_eort_displayable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=7, verbose_name='Kürzel')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('street', models.CharField(max_length=255, verbose_name='Straße')),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='PLZ')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefon')),
                ('central_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zentral-Email')),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asp-Email')),
                ('wp_user', models.BooleanField(default=False, verbose_name='WP-User')),
                ('deleted', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WZO_App.zip_code')),
            ],
        ),
        migrations.AlterField(
            model_name='rule_acc',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WZO_App.workshop'),
        ),
        migrations.AlterField(
            model_name='rule_wt',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WZO_App.workshop'),
        ),
    ]
