# Generated by Django 3.1.7 on 2021-04-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0017_auto_20210411_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='rule_wt',
            name='output',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rule_acc',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rule_wt',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Straße'),
        ),
        migrations.DeleteModel(
            name='Rule_ACC',
        ),
        migrations.DeleteModel(
            name='Rule_WT',
        ),
        migrations.AddField(
            model_name='allocation',
            name='v_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WZO_App.vehicle'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='w_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WZO_App.workshop'),
        ),
    ]
