# Generated by Django 3.1.7 on 2021-04-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0018_auto_20210411_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='a_type',
            field=models.CharField(choices=[('V', 'Verschleiß'), ('U', 'Unfall'), ('RD', 'Reifendienstleister'), ('RP', 'Reifenpartner'), ('G', 'Glasbruch')], default='V', max_length=2, verbose_name='Art'),
            preserve_default=False,
        ),
    ]
