# Generated by Django 3.1.7 on 2021-04-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0019_allocation_a_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allocation',
            unique_together={('a_type', 'v_id')},
        ),
    ]
