# Generated by Django 3.1.7 on 2021-04-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0020_auto_20210411_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='kuerzel',
            field=models.CharField(max_length=7, unique=True, verbose_name='Kürzel'),
        ),
    ]
