# Generated by Django 3.1.7 on 2021-05-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0021_auto_20210411_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleWT',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='Zeile')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Lat')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Lng')),
                ('radius', models.FloatField(blank=True, null=True, verbose_name='Radius')),
                ('lbr', models.BooleanField(default=False, verbose_name='LocationBasedRule')),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='PLZ')),
                ('make', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hersteller')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fz-Typ')),
                ('objno', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fz-ObjNr')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Baujahr')),
                ('age_operator', models.SmallIntegerField(choices=[(1, '='), (2, '<'), (3, '>')], null=True, verbose_name='Fz-Alter-Operand')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Fz-Alter')),
                ('service_contract', models.SmallIntegerField(choices=[(1, None), (2, 'Mit Servicevertrag'), (3, 'Ohne Servicevertrag')], null=True, verbose_name='Servicevertrag')),
                ('ikz', models.CharField(blank=True, max_length=255, null=True, verbose_name='IKZ')),
                ('kuerzel', models.CharField(max_length=20, verbose_name='Werkstatt-Kürzel')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bemerkung')),
            ],
        ),
    ]
