# Generated by Django 3.1.7 on 2021-05-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0023_auto_20210502_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulewt',
            name='row',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zeile'),
        ),
    ]
