# Generated by Django 3.1.7 on 2021-05-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WZO_App', '0024_auto_20210502_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulewt',
            name='age_operator',
        ),
        migrations.AlterField(
            model_name='rulewt',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fz-Alter'),
        ),
        migrations.AlterField(
            model_name='rulewt',
            name='service_contract',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Service-Vertrag'),
        ),
    ]
